import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/dark-mode/theme-provider";
import NextIntlProvider from "@/components/providers/next-intl-provider";
import { Toaster } from "@/components/ui/toaster";
import { RootLayoutProps } from "@/interface/RootLayoutProps";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale} suppressHydrationWarning translate="no">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container mx-auto px-0 max-w-full">
            {" "}
            <NextIntlProvider locale={locale}>
              {children}
              <Toaster />
            </NextIntlProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
